name: CI
on: [push,pull_request]
jobs:
  build-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build hello project
        run: |
          cd hello
          rm -rf build
          bash build-code.sh
          cd ..
      - name: Build hello-library project
        run: |
          cd hello-library
          rm -rf build
          bash build-code.sh

